const lunch = [
    {
        id: 1,
        img: '../../images/lunch-img.png',
        title: 'Бизнес-ланч “Рыбный"',
        weight: "250",
        calories: "346",
        info1: '1. Бульон куриный с лапшой и яйцом ',
        info2: '2. Рис жареный с курицей ',
        info3: '3. Салат овощной с базиликово-медовой заправкой',
        count: 0,
        price: 189,
        priceTotal: 0,
    },
    {
        id: 2,
        img: '../../images/lunch-img2.png',
        title: 'Бизнес-ланч “Мясной”',
        weight: "250",
        calories: "346",
        info1: '1. Бульон куриный с лапшой и яйцом ',
        info2: '2. Рис жареный с курицей ',
        info3: '3. Салат овощной с базиликово-медовой заправкой',
        count: 0,
        price: 189,
        priceTotal: 0,
    },
    {
        id: 3,
        img: '../../images/lunch-img.png',
        title: 'Бизнес-ланч “Рыбный"',
        weight: "250",
        calories: "346",
        info1: '1. Бульон куриный с лапшой и яйцом ',
        info2: '2. Рис жареный с курицей ',
        info3: '3. Салат овощной с базиликово-медовой заправкой',
        count: 0,
        price: 189,
        priceTotal: 0,
    },
    {
        id: 4,
        img: '../../images/lunch-img2.png',
        title: 'Бизнес-ланч “Мясной”',
        weight: "250",
        calories: "346",
        info1: '1. Бульон куриный с лапшой и яйцом ',
        info2: '2. Рис жареный с курицей ',
        info3: '3. Салат овощной с базиликово-медовой заправкой',
        count: 0,
        price: 189,
        priceTotal: 0,
    },
    {
        id: 5,
        img: '../../images/lunch-img.png',
        title: 'Бизнес-ланч “Рыбный"',
        weight: "250",
        calories: "346",
        info1: '1. Бульон куриный с лапшой и яйцом ',
        info2: '2. Рис жареный с курицей ',
        info3: '3. Салат овощной с базиликово-медовой заправкой',
        count: 0,
        price: 189,
        priceTotal: 0,
    },
    {
        id: 6,
        img: '../../images/lunch-img2.png',
        title: 'Бизнес-ланч “Мясной”',
        weight: "250",
        calories: "346",
        info1: '1. Бульон куриный с лапшой и яйцом ',
        info2: '2. Рис жареный с курицей ',
        info3: '3. Салат овощной с базиликово-медовой заправкой',
        count: 0,
        price: 189,
        priceTotal: 0,
    },

];

export default lunch;
